#set pr '{"prompt": '"${1}"'}'
pr='"Provide me name for demon"'
echo $pr
curl 'https://free-api.cveoy.top/v3/completions' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Origin: https://ai438.chagpt.link' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers' -H 'Referer: https://ai438.chagpt.link/' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"prompt":"Provide me 1 name for demon"}' >> demons.db
url1="https://free-api.cveoy.top/v3/completions"
curl $url1 -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br" -H "Referer: https://www.cveoy.com/" -H "Content-Type: application/json" -H "Origin: https://www.cveoy.com" -H "Connection: keep-alive" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" -H "TE: trailers" --data-raw '{"prompt": "Provide me 1 name for demon"}' >> demons.raw
awk -F'次数：' '{ print $2 }' demons.raw >> chatlinks
tail -n 1 chatlinks > chatlink
url2=$(awk -F'/' '{ print "https://"$3 }' chatlink)
curl $url1 -vkL -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br" -H "Referer: $url2" -H "Content-Type: application/json" -H "Origin: $url2" -H "Connection: keep-alive" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" -H "TE: trailers" --data-raw '{"prompt": "Provide me 1 name for demon"}' >> demons.raw
#curl "https://free-api.cveoy.top/v3/completions" -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" -H "Accept-Encoding: gzip, deflate, br" -H "Referer: https://www.cveoy.com/" -H "Content-Type: application/json" -H "Origin: https://www.cveoy.com" -H "Connection: keep-alive" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: cross-site" -H "TE: trailers" --data-raw '{"prompt": "Provide me 1 name for demon with stats from the next list: Strength (from 0 to 10), Intelligence(from 0 to 10), Agility(from 0 to 10), Endurance(from 0 to 10), Charisma(from 0 to 10), Mana Pool (from 0 to 100), Health Pool (from 0 to 1000) "}'
